// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlDsaqVXou8_m4Yn6HTir5LpYUUnJLAnE',
    appId: '1:853834753761:web:27cb6455ac1cc11212f9a0',
    messagingSenderId: '853834753761',
    projectId: 'lustra-ai',
    authDomain: 'lustra-ai.firebaseapp.com',
    storageBucket: 'lustra-ai.firebasestorage.app',
    measurementId: 'G-997GRC04GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlq9PYT_li-OhqRbSEJGCcX6zLftEKwTQ',
    appId: '1:853834753761:android:935b78159431a85712f9a0',
    messagingSenderId: '853834753761',
    projectId: 'lustra-ai',
    storageBucket: 'lustra-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXwbBQxcet_qHHwLkZtAohmLU_Xflq-Rc',
    appId: '1:853834753761:ios:7377bcb65adca15412f9a0',
    messagingSenderId: '853834753761',
    projectId: 'lustra-ai',
    storageBucket: 'lustra-ai.firebasestorage.app',
    androidClientId: '853834753761-6c0t5vd3be5bbjv00dl76glpcftla9kd.apps.googleusercontent.com',
    iosClientId: '853834753761-r6ch19u00ngp06j7s42n9h96koaptad9.apps.googleusercontent.com',
    iosBundleId: 'com.LustraAi.lustraAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlDsaqVXou8_m4Yn6HTir5LpYUUnJLAnE',
    appId: '1:853834753761:web:970e516c3f66c44a12f9a0',
    messagingSenderId: '853834753761',
    projectId: 'lustra-ai',
    authDomain: 'lustra-ai.firebaseapp.com',
    storageBucket: 'lustra-ai.firebasestorage.app',
    measurementId: 'G-SP7N756TBY',
  );
}
